#!/usr/bin/php
<?

array_shift($argv);

$cacheFile = getenv("HOME") . '/.phpwtf-cache';
$cache = unserialize(file_get_contents($cacheFile));

$keySlice = array_keys($cache);

foreach($argv as $searchTerm) {
  $keySlice = ' ' . implode(' ', $keySlice) . ' ';
  preg_match_all(
    "/ \w*" . $searchTerm . "\w*(?= )/", 
    $keySlice, 
    $matchSet, 
    PREG_SET_ORDER
  );
  $keySlice = array_map("array_pop", $matchSet);
}

$retMax = 0;
$nameMax = 0;

$output = Array();

foreach($matchSet as $key => $value) {
  $value = explode(' ' ,$cache[trim($value[0])]);
  printf("%-10s %s\n", array_shift($value), implode(' ', $value));
}

