#!/usr/bin/php
<?

include("ganon-read-only/ganon.php");
$manual = 'php_manual_en.html';

if(!file_exists($manual)) {
  if(!file_exists("$manual.gz")) {
    system("wget -O $manual.gz http://us1.php.net/get/php_manual_en.html.gz/from/this/mirror");
  }
  system("gunzip $manual.gz");
}
system("grep -B 4 -A 3 methodparam $manual | grep -v '^--$' > $manual.compact");

$cacheFile =  './full-table';

if(file_exists($cacheFile)) {
  $cache = unserialize(file_get_contents($cacheFile));
} else {
  $cache = Array();
}

function clean($sig) {
  $value = str_replace('( ', '(', $sig);
  $value = str_replace(' )', ')', $value);
  return preg_replace('/ ,/', ',', $value);
}
function addFunction($raw, &$cache) {
  $html = str_get_dom($raw);
  $synopsis = $html('.dc-description');
  if(!$synopsis) {
    // echo "No signature: $raw";
  } else {
    $signature = clean($synopsis[0]->getPlainText());
    $method = $html('.methodname');
    if(!$method) {
      // echo "No name: $raw";
    } else {
      $name = $method[0]->getPlainText();
      if(!isset($cache[$name])) {
        $cache[$name] = $signature;
      }
    }
  }
}

$handle = @fopen("$manual.compact", "r");
if($handle) {
  $stanza = '';
  $current = 0;
  $lc = 0;
  while (($line = fgets($handle, 8192)) !== false) {
    if(trim($line) === '') {
      if($lc > 2) {
        $current++;
        addFunction($stanza, $cache);

        if(0 === $current % 200) {
          echo "$current\n";
        }
      }
      $lc = 0;
      $stanza = '';

    } else {
      $stanza .= $line;
      $lc++;
    }
  }
} else {
  echo "Couldn't open $manual.compact";
  exit(-1);
}

file_put_contents($cacheFile, serialize($cache));
system('bzip2 -c full-table > ../reference.bz2');
